# -*- coding: utf-8 -*-
"""GST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9ZZwL5FC7LpSi2edlxkSONbromAyhHw
"""

import pandas as pd

# 上传并读取CSV文件
from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]
df = pd.read_csv(file_path, header=None)

# 手动设置列名
df.columns = ['Date', 'Debit', 'Credit', 'Description']

# 将空白单元格（NaN）替换为0
df = df.fillna(0)

# 确保 'Debit' 和 'Credit' 列被转换为数值型
df['Debit'] = pd.to_numeric(df['Debit'], errors='coerce').fillna(0)
df['Credit'] = pd.to_numeric(df['Credit'], errors='coerce').fillna(0)

# 输出处理后的数据
print(df.head())

# 适用 GST 的描述词
exclude_keywords = ['staff salary', 'bank', 'director fee', 'Bank Fee', ]

# 过滤掉不适用 GST 的交易
df['GST Applicable'] = ~df['Description'].str.contains('|'.join(exclude_keywords), case=False, na=False)

# 适用于 GST 的交易
gst_applicable = df[df['GST Applicable']]

# 计算进账和支出的 GST
total_credit = df['Credit'].sum()  # 进账总额
total_debit = df['Debit'].sum()    # 支出总额

# 输出进账和支出总额
print(f"所有交易的进账总和 (Credit): {total_credit:.2f}")
print(f"所有交易的支出总和 (Debit): {total_debit:.2f}")

# 适用于 GST 的进账和支出
gst_credit = gst_applicable['Credit'].sum()  # 进账的 GST
gst_debit = gst_applicable['Debit'].sum()    # 支出的 GST

# 输出适用 GST 的进账和支出总额
print(f"适用 GST 的进账总和 (Credit): {gst_credit:.2f}")
print(f"适用 GST 的支出总和 (Debit): {gst_debit:.2f}")

# 计算 GST
income_gst = gst_credit * 0.1  # 进账 GST
expense_gst = gst_debit * 0.1  # 支出 GST
net_gst = income_gst - expense_gst  # 应缴纳的净 GST

# 输出 GST 计算结果
print("\n所有交易的 GST 计算:")
print(f"进账 GST: {income_gst:.2f}")
print(f"支出 GST: {expense_gst:.2f}")
print(f"应缴纳 GST: {net_gst:.2f}")
!git status